### ISSUE TITLE
Suggestion: Energy Cell production should not have secondary resources

### ISSUE THREAD

**Issue by Vectorial1024** [DeadAirRT/deadair_eco#5]
This seems like a huge breakaway from the idea of secondary resources, but hear me out:

- Vanilla 7.0 now has variable sunlight levels in vanilla sectors
  - Station placement should be important
  - E-cell production should be boosted by good placement, but not on other factors
- Lore-wise, energy cell production mostly depends on sunlight
  - The workforce is there to tune and maintain the energy array modules, and should only provide just a bit of extra bonus (see vanilla x1.43; even I feel x1.43 is a bit too much)
  - It really should depend mostly on the environment, just like mineral/gas collection
  - It is just stupid, e.g. in Avarice, that providing secondary resources will result in an x2 production of e-cells, on top of the extra-high sunlight in Avarice
- The ease of e-cell production is already balanced by the high cost of the module (assuming the module was not scanned via data leaks)

Therefore, I am suggesting to remove the secondary resource requirement of E-cell production.

**Comment by DeadAirRT** [comment]
I'll consider it but my initial thoughts on it:
Why should arbitrary values that egosoft determined and didn't implement logic to optimize be the only controlling factor on how many EC are produced? I do like the idea of certain sectors being more valuable due to resources/sunlight but until the logic actually prioritizes those systems for conquest etc then it's basically a player only feature.

**Comment by DeadAirRT** [comment]
EC are still using secondary wares.
